package org.graalvm.vm.trcview.analysis.device;

public enum DeviceType {
    PROCESSOR("Processor"), // coprocessors, ...
    MEMORY("Memory"), // MMU, MPU, ...
    SOUND("Sound"), // synth voice, mic, speaker, ...
    VIDEO("Video"), // camera, capture card, ...
    GRAPHICS("Graphics"), // 2D engine, 3D engine, ...
    DISPLAY("Display"), // LCD display, VGA controller, ...
    PRINTER("Printer"), // printers, obviously
    KEYBOARD("Keyboard"), // keyboards, buttons, ...
    POINTING("Pointing device"), // mouse, IR pointer, touchscreen, ...
    CONTROLLER("Controller"), // game controllers, control surfaces, ...
    NETWORK("Network"), // ethernet/WLAN/WiMAX/...
    STORAGE("Storage"), // floppy disk controllers, hard disk controllers, flash controllers, ...
    INTERFACE("Interface"), // serial line interfaces, DACs, ADCs, ...
    BUS("Bus"); // QBUS, I2C, SPI, ...

    private final String name;

    private DeviceType(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
